<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1152" started-at="2020-07-01T18:29:23Z" finished-at="2020-07-01T18:29:24Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="1152" started-at="2020-07-01T18:29:23Z" finished-at="2020-07-01T18:29:24Z">
      <class name="TestAuto.TechAutoTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:TestAuto.TechAutoTest@589838eb]" name="beforeMethod" is-config="true" duration-ms="9488" started-at="2020-07-01T23:59:14Z" finished-at="2020-07-01T23:59:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="AdditionTest()[pri:0, instance:TestAuto.TechAutoTest@589838eb]" name="AdditionTest" duration-ms="43" started-at="2020-07-01T23:59:23Z" finished-at="2020-07-01T23:59:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdditionTest -->
        <test-method status="FAIL" signature="SubractionTest()[pri:1, instance:TestAuto.TechAutoTest@589838eb]" name="SubractionTest" duration-ms="8" started-at="2020-07-01T23:59:24Z" finished-at="2020-07-01T23:59:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at TestAuto.TechAutoTest.SubractionTest(TechAutoTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubractionTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:TestAuto.TechAutoTest@589838eb]" name="quit" is-config="true" duration-ms="1124" started-at="2020-07-01T23:59:25Z" finished-at="2020-07-01T23:59:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- TestAuto.TechAutoTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
